# Generated by Django 6.0.5 on 2026-05-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_initials', models.CharField(max_length=3)),
                ('score', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score', 'created_at'],
                'indexes': [models.Index(fields=['-score'], name='game_score_score_eae92f_idx')],
            },
        ),
    ]
